import {
  AudioWaveform,
  Blocks,
  Calendar,
  Command,
  Home,
  Inbox,
  MessageCircleQuestion,
  Search,
  Settings2,
  Sparkles,
  Trash2,
} from "lucide-react";
import { Book } from "lucide-react";

export const links = [
  {
    title: "Classes",
    url: "/dashboard/classes",
    icon: Book, // Icon for the link
    badge: "New", // Badge text
  },
  {
    title: "Assignments",
    url: "/dashboard/assignments",
    icon: Book,
    badge: "Due",
  },
  {
    title: "Exams",
    url: "/dashboard/exams",
    icon: Book,
    badge: "Upcoming",
  },
  {
    title: "Results",
    url: "/dashboard/results",
    icon: Book,
    badge: "Updated",
  },
];

export const data = {
  navMain: [
    {
      title: "Search",
      url: "#",
      icon: Search,
    },
    {
      title: "Ask AI",
      url: "/ai",
      icon: Sparkles,
    },
    {
      title: "Home",
      url: "/",
      icon: Home,
      isActive: true,
    },
    {
      title: "Inbox",
      url: "#",
      icon: Inbox,
      badge: "10",
    },
  ],
  navSecondary: [
    {
      title: "Calendar",
      url: "#",
      icon: Calendar,
    },
    {
      title: "Settings",
      url: "#",
      icon: Settings2,
    },
    {
      title: "Templates",
      url: "#",
      icon: Blocks,
    },
    {
      title: "Trash",
      url: "#",
      icon: Trash2,
    },
    {
      title: "Help",
      url: "#",
      icon: MessageCircleQuestion,
    },
  ],
};


export const books = [
  {
    id: 1,
    title: "Riyadh as-Salihin",
    author: "Imam Nawawi",
    category: "Hadith",
    price: 0,
    readCount: 120,
    rating: 5.0,
    image: "/images/img-2.jpeg",
  },
  {
    id: 2,
    title: "The Fundamentals of Tawheed",
    author: "Dr. Bilal Philips",
    category: "Aqidah",
    price: 5,
    readCount: 45,
    rating: 4.5,
    image: "/images/img-2.jpeg",
  },
  {
    id: 3,
    title: "In the Footsteps of the Prophet",
    author: "Tariq Ramadan",
    category: "Seerah",
    price: 5,
    readCount: 60,
    rating: 2.5,
    image: "/images/img-2.jpeg",
  },
  {
    id: 4,
    title: "Fortress of the Muslim",
    author: "Sa'id bin Wahf al-Qahtani",
    category: "Dua",
    price: 0,
    readCount: 220,
    rating: 5.0,
    image: "/images/img-2.jpeg",
  },
  {
    id: 5,
    title: "Don't Be Sad",
    author: "Dr. Aaidh al-Qarni",
    category: "Self-help",
    price: 10,
    readCount: 180,
    rating: 4.7,
    image: "/images/img-2.jpeg",
  },
  {
    id: 6,
    title: "La Tahzan (Don't Be Sad)",
    author: "Dr. Aaidh al-Qarni",
    category: "Motivation",
    price: 8,
    readCount: 90,
    rating: 4.2,
    image: "/images/img-2.jpeg",
  },
  {
    id: 7,
    title: "Stories of the Prophets",
    author: "Ibn Kathir",
    category: "History",
    price: 0,
    readCount: 150,
    rating: 5.0,
    image: "/images/img-2.jpeg",
  },
  {
    id: 8,
    title: "Fiqh-us-Sunnah",
    author: "Sayyid Sabiq",
    category: "Fiqh",
    price: 15,
    readCount: 75,
    rating: 4.6,
    image: "/images/img-2.jpeg",
  },
  {
    id: 9,
    title: "The Sealed Nectar",
    author: "Safiyyur-Rahman al-Mubarakpuri",
    category: "Seerah",
    price: 12,
    readCount: 210,
    rating: 4.9,
    image: "/images/img-2.jpeg",
  },
  {
    id: 10,
    title: "Tafsir Ibn Kathir",
    author: "Ibn Kathir",
    category: "Tafsir",
    price: 0,
    readCount: 300,
    rating: 5.0,
    image: "/images/img-2.jpeg",
  },
  {
    id: 11,
    title: "The Book of Manners",
    author: "Fu'ad Ibn 'Abd Al-'Azeez Ash-Shulhoob",
    category: "Akhlaq",
    price: 5,
    readCount: 100,
    rating: 4.4,
    image: "/images/img-2.jpeg",
  },
  {
    id: 12,
    title: "The Life of Muhammad",
    author: "Muhammad Husayn Haykal",
    category: "Biography",
    price: 10,
    readCount: 95,
    rating: 4.3,
    image: "/images/img-2.jpeg",
  },
  {
    id: 13,
    title: "Explanation of the Three Fundamental Principles",
    author: "Shaykh Muhammad ibn Saalih al-Uthaymeen",
    category: "Aqidah",
    price: 6,
    readCount: 55,
    rating: 4.6,
    image: "/images/img-2.jpeg",
  },
  {
    id: 14,
    title: "The Creed of Imam Tahawi",
    author: "Imam Abu Ja'far al-Tahawi",
    category: "Aqidah",
    price: 7,
    readCount: 40,
    rating: 4.1,
    image: "/images/img-2.jpeg",
  },
  {
    id: 15,
    title: "Purification of the Heart",
    author: "Hamza Yusuf",
    category: "Tazkiyah",
    price: 9,
    readCount: 65,
    rating: 4.7,
    image: "/images/img-2.jpeg",
  },
  {
    id: 16,
    title: "The Path to Guidance",
    author: "Ibn Qudamah al-Maqdisi",
    category: "Spirituality",
    price: 5,
    id: 17,
    title: "Kitab al-Tawheed",
    author: "Muhammad ibn Abdul Wahhab",
    category: "Aqidah",
    price: 0,
    readCount: 140,
    rating: 4.9,
    image: "/images/img-2.jpeg",
  },
  {
    id: 18,
    title: "The Ideal Muslimah",
    author: "Dr. Muhammad Ali Al-Hashimi",
    category: "Women",
    price: 10,
    readCount: 110,
    rating: 4.8,
    image: "/images/img-2.jpeg",
  },
  {
    id: 19,
    title: "The Ideal Muslim",
    author: "Dr. Muhammad Ali Al-Hashimi",
    category: "Men",
    price: 10,
    readCount: 70,
    rating: 4.6,
    image: "/images/img-2.jpeg",
  },
  {
    id: 20,
    title: "Al-Adab Al-Mufrad",
    author: "Imam Bukhari",
    category: "Hadith",
    price: 0,
    readCount: 130,
    rating: 5.0,
    image: "/images/img-2.jpeg",
  },
  {
    id: 21,
    title: "Signs Before the Day of Judgment",
    author: "Ibn Kathir",
    category: "End Times",
    price: 5,
    readCount: 125,
    rating: 4.3,
    image: "/images/img-2.jpeg",
  },
  {
    id: 22,
    title: "A Brief Illustrated Guide to Understanding Islam",
    author: "I.A. Ibrahim",
    category: "Introductory",
    price: 0,
    readCount: 200,
    rating: 4.5,
    image: "/images/img-2.jpeg",
  },
  {
    id: 23,
    title: "Enjoy Your Life",
    author: "Dr. Muhammad al-Arifi",
    category: "Self-help",
    price: 6,
    readCount: 85,
    rating: 4.7,
    image: "/images/img-2.jpeg",
  },
];